# Generated by Django 5.1.1 on 2024-11-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name_plural': 'Postagens'},
        ),
    ]
