# Generated by Django 5.1.4 on 2024-12-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
