# Generated by Django 5.1.4 on 2025-02-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('descricao', models.TextField(blank=True, max_length=50, null=True)),
                ('estoque', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'produtos',
            },
        ),
    ]
