# Generated by Django 5.1.4 on 2025-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
