# Generated by Django 5.1.2 on 2025-02-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_produto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('vendas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despesas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
    ]
