# Generated by Django 5.1.2 on 2025-02-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_registrofinanceiro_remove_produto_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrofinanceiro',
            options={'verbose_name_plural': 'Registros Financeiros'},
        ),
    ]
