# Generated by Django 5.1.2 on 2025-02-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_registrofinanceiro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrofinanceiro',
            options={'verbose_name_plural': 'Registros_Financeiros'},
        ),
    ]
