# Generated by Django 5.1.2 on 2025-02-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_registrofinanceiro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(auto_now_add=True)),
                ('vendas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despesas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'RegistrosFinanceiros',
            },
        ),
        migrations.DeleteModel(
            name='RegistroFinanceiro',
        ),
    ]
