# Generated by Django 5.1.2 on 2025-02-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_registrosfinanceiro_delete_registrofinanceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_comprado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
