# Generated by Django 5.1.2 on 2025-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_comprado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
