# Generated by Django 5.1.2 on 2025-03-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_produto_preco_alter_produto_preco_comprado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrosfinanceiro',
            options={},
        ),
    ]
