# Generated by Django 5.1.2 on 2025-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_registrosfinanceiro_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.DateField(auto_now_add=True),
        ),
    ]
