# Generated by Django 5.1.2 on 2025-03-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_funcionarios/')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=10, unique=True)),
                ('data_admissao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=20)),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
