# Generated by Django 5.1.2 on 2025-03-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_funcionario_delete_transacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='nacionalidade',
        ),
    ]
