# Generated by Django 5.1.2 on 2025-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
