# Generated by Django 5.1.2 on 2025-03-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_funcionario_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
