# Generated by Django 5.1.2 on 2025-03-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_produto_categoria_registrosfinanceiro_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
