# Generated by Django 5.1.7 on 2025-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_produto_categoria_funcionario_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='March', max_length=20),
        ),
    ]
