# Generated by Django 5.1.7 on 2025-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_registrosfinanceiro_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='09/03/2025', max_length=20),
        ),
    ]
