# Generated by Django 5.1.7 on 2025-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_registrosfinanceiro_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='em_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
