# Generated by Django 5.1.7 on 2025-03-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_produto_desconto_produto_em_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='desconto',
        ),
    ]
