# Generated by Django 5.1.7 on 2025-03-10 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_produto_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='10/03/2025', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.funcionario')),
            ],
        ),
    ]
