# Generated by Django 5.1.7 on 2025-03-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_registrosfinanceiro_mes_historicopagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='status',
            new_name='status_pagamento',
        ),
    ]
