# Generated by Django 5.1.7 on 2025-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_rename_status_funcionario_status_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='13/03/2025', max_length=20),
        ),
    ]
