# Generated by Django 5.1.2 on 2025-07-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_registrosfinanceiro_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Sem categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='21/07/2025', max_length=20),
        ),
    ]
