# Generated by Django 5.1.2 on 2025-07-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_produto_categoria_alter_registrosfinanceiro_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='data',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='postagem',
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.CharField(default='Anônimo', max_length=100),
        ),
        migrations.AddField(
            model_name='comentario',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.produto'),
        ),
    ]
