# Generated by Django 5.1.2 on 2025-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_comentario_autor_comentario_data_postagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.CharField(default='Anônimo', max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='22/07/2025', max_length=20),
        ),
    ]
