# Generated by Django 5.1.2 on 2025-07-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_comentario_autor_alter_comentario_data_postagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='24/07/2025', max_length=20),
        ),
    ]
