# Generated by Django 5.1.2 on 2025-07-29 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_registrosfinanceiro_mes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='mensagem',
            field=models.CharField(default='Nova venda realizada', max_length=255),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.produto'),
        ),
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='29/07/2025', max_length=20),
        ),
    ]
