# Generated by Django 5.1.2 on 2025-07-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_rename_data_criacao_notificacao_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='vendedor',
        ),
    ]
