# Generated by Django 5.1.2 on 2025-08-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_remove_pedido_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosfinanceiro',
            name='mes',
            field=models.CharField(default='23/08/2025', max_length=20),
        ),
    ]
