# Generated by Django 5.1.2 on 2025-03-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_carrinho_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='data_adicionado',
        ),
    ]
