# Generated by Django 5.2.1 on 2025-07-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_itemcarrinho_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data',
            new_name='data_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='home.itemcarrinho'),
        ),
    ]
