# Generated by Django 5.1.2 on 2025-07-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comentariosite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='comentariosite',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='comentariosite',
            name='data',
        ),
        migrations.RemoveField(
            model_name='comentariosite',
            name='foto',
        ),
        migrations.AddField(
            model_name='comentariosite',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-24 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentariosite',
            name='nota',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
