# Generated by Django 5.1.2 on 2025-07-29 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificacao',
            new_name='NotificacaoUsuario',
        ),
        migrations.RenameField(
            model_name='notificacaousuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
